export const ROUTES = {
  LOGIN: '/login',
  HOME: '/',
  DASHBOARD: '/',
  PROJECTS: '/projects',
  PROJECT_DETAIL: (id: string) => `/projects/${id}`,
  TASKS: '/tasks',
  DAILY_REPORTS: '/daily-reports',
  ISSUES: '/issues',
  BUDGET: '/budget',
  SUPPLIERS: '/procurement/suppliers',
  PURCHASE_ORDERS: '/procurement/orders',
  DELIVERIES: '/procurement/deliveries',
  DOCUMENTS: '/documents',
  AI_INSIGHTS: '/ai/insights',
  AI_ASSISTANT: '/ai/assistant',
  SETTINGS: '/settings',
  PROFILE: '/profile',
} as const;
